---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-eu-mgmt
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
stringData:
  config: |
    {"tlsClientConfig":{"insecure":false}}
  name: eu-mgmt
  server: https://kubernetes.default.svc
type: Opaque