apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: vault-cn
spec:
  # 1. Set size to 1 for non-HA single node
  size: 1
  image: hashicorp/vault:1.18
  bankVaultsImage: ghcr.io/bank-vaults/bank-vaults:v1.32.0
  serviceAccount: vault-infra

  # 2. Remove Pod Anti-Affinity (not relevant for size: 1)
  podAntiAffinity: "" 
  serviceType: ClusterIP

  resources:
    vault:
      requests:
        cpu: 25m
        memory: 500Mi
      limits:
        memory: 800Mi
        cpu: 120m

  secretInitsConfig:
    - name: SKIP_CHOWN
      value: "true"

  vaultInitContainers:
    - name: config-permission
      image: docker.io/library/busybox:latest
      command:
        - /bin/sh
        - -c
        - "chmod g+r,o+r /vault/config/vault.json"
      volumeMounts:
        - mountPath: /vault/config
          name: vault-config
      resources:
        requests:
          cpu: 25m
          memory: 64Mi

  # 3. Removed volumeClaimTemplates for file backend, relying on default EmptyDir for /vault/file

  volumes:
    # Retain the audit logs PVC
    - name: vault-audit-logs
      persistentVolumeClaim:
        claimName: vault-audit-logs
  
  volumeMounts:
    # The 'vault-raft' PVC mount is gone, replaced by a simple EmptyDir for file storage (default behavior)
    - name: vault-audit-logs
      mountPath: /vault/audit

  unsealConfig:
    kubernetes:
      secretNamespace: vault

  caNamespaces: ["*"]

  config:
    cluster_name: cn-vault
    ui: true
    storage:
      # 4. Use file storage backend
      file:
        path: /vault/file
    seal:
      shamir:
        secret_shares: 1
        secret_threshold: 1
    listener:
      tcp:
        address: "[::]:8200"
        # 5. Remove HA/Cluster address entirely for single node
        # cluster_address: "[::]:8201" 

        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key

        telemetry:
          unauthenticated_metrics_access: true
    telemetry:
      disable_hostname: true
      prometheus_retention_time: "24h"

    api_addr: https://vault-cn.vault:8200
    # 6. Remove HA cluster address reference
    # cluster_addr: "https://${.Env.POD_NAME}:8201"

    log_format: json

  serviceRegistrationEnabled: true
  serviceMonitorEnabled: true
  statsdDisabled: true

  externalConfig:
    purgeUnmanagedConfig:
      enabled: true
      exclude:
        secrets: true
        auth: true
    audit:
      - type: file
        options:
          file_path: stdout
          hmac_accessor: "false"
          log_raw: "true"
    # Policies and Auth configuration remain the same
    policies:
      - name: admin
        rules: |
          path "sys/leases/*"
          {
            capabilities = ["create", "read", "update", "delete", "list", "sudo"]
          }

          path "auth/*"
          {
            capabilities = ["create", "read", "update", "delete", "list", "sudo"]
          }

          path "sys/auth/*"
          {
            capabilities = ["create", "update", "delete", "sudo"]
          }

          path "sys/auth"
          {
            capabilities = ["read"]
          }

          path "sys/policies/acl"
          {
            capabilities = ["read","list"]
          }

          path "sys/policies/acl/*"
          {
            capabilities = ["create", "read", "update", "delete", "list", "sudo"]
          }

          path "secret/*"
          {
            capabilities = ["create", "read", "update", "delete", "list", "sudo"]
          }

          path "sys/mounts/*"
          {
            capabilities = ["create", "read", "update", "delete", "list", "sudo"]
          }

          path "sys/mounts"
          {
            capabilities = ["read"]
          }

          path "sys/health"
          {
            capabilities = ["read", "sudo"]
          }
      - name: readonly_secrets
        rules: |
          path "secret/*" {
            capabilities = ["read", "list"]
          }

      - name: kube_mgmt_namespaced
        rules: |
          path "secret/data/kubernetes/mgmt/{{ printf "{{identity.entity.aliases.auth_kubernetes_958ce766.metadata.service_account_namespace}}" }}/*" {
            capabilities = ["read", "list"]
          }

    auth:
      - type: kubernetes
        roles:
          - name: default
            bound_service_account_names: ["*"]
            bound_service_account_namespaces: ["*"]
            policies: kube_mgmt_namespaced
            ttl: 1h

    secrets:
      - type: kv
        path: secret
        options:
          version: 2
        configuration:
          config:
            - max_versions: 3