apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: vault-cn
spec:
  # 1. Single node size
  size: 1
  image: hashicorp/vault:1.18

  #bankVaultsImage: ghcr.io/bank-vaults/bank-vaults:v1.32.0
  # Setting this to empty string AND removing unsealConfig will stop the sidecar
  bankVaultsImage: ""

  serviceAccount: vault-infra

  # 2. Clear out HA-related fields
  podAntiAffinity: "" 
  serviceType: ClusterIP

  resources:
    vault:
      requests:
        cpu: 25m
        memory: 500Mi
      limits:
        memory: 800Mi
        cpu: 120m

  secretInitsConfig:
    - name: SKIP_CHOWN
      value: "true"

  vaultInitContainers:
    - name: config-permission
      image: docker.io/library/busybox:latest
      command:
        - /bin/sh
        - -c
        - "chmod g+r,o+r /vault/config/vault.json"
      volumeMounts:
        - mountPath: /vault/config
          name: vault-config
      resources:
        requests:
          cpu: 25m
          memory: 64Mi

  volumes:
    # Retain the audit logs PVC
    - name: vault-audit-logs
      persistentVolumeClaim:
        claimName: vault-audit-logs
    # Explicit EmptyDir for file storage (temporary, non-persistent)
    - name: vault-file
      emptyDir: {}

  volumeMounts:
    - name: vault-audit-logs
      mountPath: /vault/audit
    # Mount for file storage backend
    - name: vault-file
      mountPath: /vault/file


  # unsealConfig:
  #   kubernetes:
  #     secretNamespace: vault

  caNamespaces: ["*"]

  config:
    cluster_name: cn-vault
    ui: true
    storage:
      # Use file storage backend
      file:
        path: /vault/file
    seal:
      # Set shares/threshold to 1/1 for easiest manual unsealing
      shamir:
        secret_shares: 1
        secret_threshold: 1
    listener:
      tcp:
        address: "[::]:8200"
        # cluster_address is omitted here as it's not needed for file storage
        
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key

        telemetry:
          unauthenticated_metrics_access: true
    telemetry:
      disable_hostname: true
      prometheus_retention_time: "24h"

    api_addr: https://vault-cn.vault:8200
    # cluster_addr is omitted
    log_format: json

  # CRITICAL CHANGE: Disables cluster-aware internal service management/orchestration.
  serviceRegistrationEnabled: false 
  serviceMonitorEnabled: true
  statsdDisabled: true

  # externalConfig:
  #   purgeUnmanagedConfig:
  #     enabled: true
  #     exclude:
  #       secrets: true
  #       auth: true
  #   audit:
  #     - type: file
  #       options:
  #         file_path: stdout
  #         hmac_accessor: "false"
  #         log_raw: "true"
  #   policies:
  #     - name: admin
  #       rules: |
  #         path "sys/leases/*"
  #         {
  #           capabilities = ["create", "read", "update", "delete", "list", "sudo"]
  #         }

  #         path "auth/*"
  #         {
  #           capabilities = ["create", "read", "update", "delete", "list", "sudo"]
  #         }

  #         path "sys/auth/*"
  #         {
  #           capabilities = ["create", "update", "delete", "sudo"]
  #         }

  #         path "sys/auth"
  #         {
  #           capabilities = ["read"]
  #         }

  #         path "sys/policies/acl"
  #         {
  #           capabilities = ["read","list"]
  #         }

  #         path "sys/policies/acl/*"
  #         {
  #           capabilities = ["create", "read", "update", "delete", "list", "sudo"]
  #         }

  #         path "secret/*"
  #         {
  #           capabilities = ["create", "read", "update", "delete", "list", "sudo"]
  #         }

  #         path "sys/mounts/*"
  #         {
  #           capabilities = ["create", "read", "update", "delete", "list", "sudo"]
  #         }

  #         path "sys/mounts"
  #         {
  #           capabilities = ["read"]
  #         }

  #         path "sys/health"
  #         {
  #           capabilities = ["read", "sudo"]
  #         }
  #     - name: readonly_secrets
  #       rules: |
  #         path "secret/*" {
  #           capabilities = ["read", "list"]
  #         }

  #     - name: kube_mgmt_namespaced
  #       rules: |
  #         path "secret/data/kubernetes/mgmt/{{ printf "{{identity.entity.aliases.auth_kubernetes_958ce766.metadata.service_account_namespace}}" }}/*" {
  #           capabilities = ["read", "list"]
  #         }

  #   auth:
  #     - type: kubernetes
  #       roles:
  #         - name: default
  #           bound_service_account_names: ["*"]
  #           bound_service_account_namespaces: ["*"]
  #           policies: kube_mgmt_namespaced
  #           ttl: 1h

  #   secrets:
  #     - type: kv
  #       path: secret
  #       options:
  #         version: 2
  #       configuration:
  #         config:
  #           - max_versions: 3